import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import { ExpressiveCodeTheme } from "@astrojs/starlight/expressive-code";
import { readFileSync } from "node:fs";

const zincFrost = ExpressiveCodeTheme.fromJSONString(
  readFileSync(new URL("./src/themes/zinc-frost.json", import.meta.url), "utf-8"),
);

// Code frames are dark plates in both site themes.
const plate = {
  bg: "#14171b",
  bar: "#181b20",
  line: "#252a31",
  mute: "#7d889a",
};

const page = (label, link) => ({ label, link });

export default defineConfig({
  site: "https://zinc.carbonsoft.sh",
  redirects: {
    "/getting-started/installation": "/guide/installation",
    "/getting-started/quick-start": "/guide/quickstart",
    "/getting-started/first-route": "/guide/first-route",
    "/guide/error-handling": "/guide/errors",
    "/guide/response": "/guide/responses-and-rendering",
    "/cookbook/hello-world": "/guide/quickstart",
    "/cookbook/cors": "/middleware/cors",
    "/cookbook/http2-server-push": "/cookbook/http2",
    "/cookbook/jsonp": "/guide/responses-and-rendering",
    "/cookbook/load-balancing": "/middleware/proxy",
    "/cookbook/subdomain": "/guide/routing",
  },
  integrations: [
    starlight({
      title: "Zinc",
      favicon: "/favicon.png?v=20260923",
      customCss: ["./src/styles/zinc.css"],
      editLink: {
        baseUrl: "https://github.com/0mjs/zinc/edit/dev/website/",
      },
      lastUpdated: true,
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/0mjs/zinc",
        },
      ],
      components: {
        Footer: "./src/components/Footer.astro",
        SiteTitle: "./src/components/SiteTitle.astro",
        PageTitle: "./src/components/PageTitle.astro",
      },
      head: [
        {
          tag: "script",
          content:
            "try{if(!localStorage.getItem('starlight-theme')){localStorage.setItem('starlight-theme','dark');document.documentElement.dataset.theme='dark';}}catch(e){document.documentElement.dataset.theme='dark';}",
        },
        {
          tag: "link",
          attrs: { rel: "preconnect", href: "https://fonts.googleapis.com" },
        },
        {
          tag: "link",
          attrs: { rel: "apple-touch-icon", href: "/apple-touch-icon.png" },
        },
        {
          tag: "link",
          attrs: {
            rel: "preconnect",
            href: "https://fonts.gstatic.com",
            crossorigin: true,
          },
        },
        {
          tag: "link",
          attrs: {
            rel: "stylesheet",
            href: "https://fonts.googleapis.com/css2?family=Michroma&family=Instrument+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400&display=swap",
          },
        },
      ],
      sidebar: [
        {
          label: "Guide",
          collapsed: true,
          items: [
            page("Quickstart", "/guide/quickstart/"),
            page("Installation", "/guide/installation/"),
            page("Your First Route", "/guide/first-route/"),
            page("Routing", "/guide/routing/"),
            page("Request Data", "/guide/request/"),
            page("Binding", "/guide/binding/"),
            page("Context", "/guide/context/"),
            page("Responses and Rendering", "/guide/responses-and-rendering/"),
            page("Errors", "/guide/errors/"),
            page("Groups and Middleware", "/guide/groups-and-middleware/"),
            page("Zinc and net/http", "/guide/http-interoperability/"),
            page("Static Files", "/guide/static-files/"),
            page("Templates", "/guide/templates/"),
            page("Cookies", "/guide/cookies/"),
            page("Testing", "/guide/testing/"),
            page("Configuration", "/guide/configuration/"),
            page("Client IP and Proxies", "/guide/ip-address/"),
            page("Customization", "/guide/customization/"),
            page("Benchmarks", "/extra/benchmarks/"),
            page("FAQ", "/extra/faq/"),
            page("Migrating to 0.2", "/extra/migration-0.2/"),
          ],
        },
        {
          label: "API Reference",
          collapsed: true,
          items: [
            page("Application", "/api/app/"),
            page("Configuration", "/api/config/"),
            page("Context", "/api/context/"),
            page("Binding", "/api/binding/"),
            page("Errors", "/api/errors/"),
            page("Groups", "/api/group/"),
            page("Response Writer", "/api/response-writer/"),
          ],
        },
        {
          label: "Middleware",
          collapsed: true,
          items: [
            page("All Middleware", "/middleware/overview/"),
            page("Request ID", "/middleware/request-id/"),
            page("Request Logger", "/middleware/request-logger/"),
            page("Recover", "/middleware/recover/"),
            page("Secure Headers", "/middleware/secure/"),
            page("CORS", "/middleware/cors/"),
            page("Body Limit", "/middleware/body-limit/"),
            page("Context Timeout", "/middleware/context-timeout/"),
            page("Rate Limiter", "/middleware/rate-limiter/"),
            page("Basic Auth", "/middleware/basic-auth/"),
            page("Key Auth", "/middleware/key-auth/"),
            page("JWT", "/middleware/jwt/"),
            page("Session", "/middleware/session/"),
            page("CSRF", "/middleware/csrf/"),
            page("Casbin Auth", "/middleware/casbin-auth/"),
            page("Header Guards", "/middleware/header-guards/"),
            page("Gzip", "/middleware/gzip/"),
            page("Decompress", "/middleware/decompress/"),
            page("Static", "/middleware/static/"),
            page("Proxy", "/middleware/proxy/"),
            page("Prometheus", "/middleware/prometheus/"),
            page("OpenTelemetry", "/middleware/open-telemetry/"),
            page("Jaeger", "/middleware/jaeger/"),
            page("pprof", "/middleware/pprof/"),
            page("Body Dump", "/middleware/body-dump/"),
            page("Rewrite", "/middleware/rewrite/"),
            page("Redirect", "/middleware/redirect/"),
            page("Method Override", "/middleware/method-override/"),
            page("Trailing Slash", "/middleware/trailing-slash/"),
            page("Utility", "/middleware/utility/"),
          ],
        },
        {
          label: "Cookbook",
          collapsed: true,
          items: [
            page("All Recipes", "/cookbook/"),
            page("CRUD API", "/cookbook/crud/"),
            page("SQLite CRUD API", "/cookbook/sqlite-crud-api/"),
            page("Signed Webhooks", "/cookbook/signed-webhook/"),
            page("Health and Readiness", "/cookbook/health-readiness/"),
            page("Structured Logs with slog", "/cookbook/structured-logging/"),
            page("Graceful Shutdown", "/cookbook/graceful-shutdown/"),
            page("Automatic TLS", "/cookbook/auto-tls/"),
            page("HTTP/2 Server", "/cookbook/http2/"),
            page("Reverse Proxy", "/cookbook/reverse-proxy/"),
            page("Timeouts", "/cookbook/timeout/"),
            page("Adopt Zinc in net/http", "/cookbook/existing-net-http-service/"),
            page("Embed Resources", "/cookbook/embed-resources/"),
            page("File Upload", "/cookbook/file-upload/"),
            page("File Download", "/cookbook/file-download/"),
            page("Templ UI", "/cookbook/templ-ui/"),
            page("Templated HTML + JS", "/cookbook/templated-html-js-page/"),
            page("Server-Sent Events", "/cookbook/sse/"),
            page("Streaming Response", "/cookbook/streaming-response/"),
            page("WebSocket", "/cookbook/websocket/"),
            page("JWT", "/cookbook/jwt/"),
            page("Custom Middleware", "/cookbook/middleware/"),
          ],
        },
      ],
      expressiveCode: {
        themes: [zincFrost],
        useStarlightDarkModeSwitch: false,
        useStarlightUiThemeColors: false,
        styleOverrides: {
          borderRadius: "6px",
          borderColor: plate.line,
          codeFontFamily: "var(--sl-font-mono)",
          codeFontSize: "0.8rem",
          codeLineHeight: "1.7",
          codePaddingBlock: "1rem",
          codePaddingInline: "1.15rem",
          uiFontFamily: "var(--sl-font-mono)",
          scrollbarThumbColor: "#2c323a",
          scrollbarThumbHoverColor: "#3a414b",
          frames: {
            frameBoxShadowCssValue: "none",
            editorBackground: plate.bg,
            editorTabBarBackground: plate.bar,
            editorTabBarBorderColor: "transparent",
            editorTabBarBorderBottomColor: plate.line,
            editorActiveTabBackground: plate.bar,
            editorActiveTabForeground: "#aeb8c6",
            editorActiveTabBorderColor: "transparent",
            editorActiveTabIndicatorTopColor: "transparent",
            editorActiveTabIndicatorBottomColor: "transparent",
            editorTabBorderRadius: "0",
            terminalBackground: plate.bg,
            terminalTitlebarBackground: plate.bar,
            terminalTitlebarForeground: plate.mute,
            terminalTitlebarBorderBottomColor: plate.line,
            terminalTitlebarDotsForeground: "#aeb8c6",
            terminalTitlebarDotsOpacity: "1",
            inlineButtonBackground: "#d8dee9",
            inlineButtonForeground: "#aeb8c6",
            inlineButtonBorder: plate.line,
            inlineButtonBorderOpacity: "1",
            tooltipSuccessBackground: "#d8dee9",
            tooltipSuccessForeground: plate.bg,
          },
        },
      },
    }),
  ],
});
