// Package petclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package petclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreatePetBodyKind.
const (
	CreatePetBodyKindCat CreatePetBodyKind = "cat"
	CreatePetBodyKindDog CreatePetBodyKind = "dog"
)

// Valid indicates whether the value is a known member of the CreatePetBodyKind enum.
func (e CreatePetBodyKind) Valid() bool {
	switch e {
	case CreatePetBodyKindCat:
		return true
	case CreatePetBodyKindDog:
		return true
	default:
		return false
	}
}

// Defines values for PetKind.
const (
	PetKindCat PetKind = "cat"
	PetKindDog PetKind = "dog"
)

// Valid indicates whether the value is a known member of the PetKind enum.
func (e PetKind) Valid() bool {
	switch e {
	case PetKindCat:
		return true
	case PetKindDog:
		return true
	default:
		return false
	}
}

// Error The error body Zinc's default error handler writes.
type Error struct {
	Error struct {
		// Details Details added with HTTPError.Details.
		Details *map[string]interface{} `json:"details,omitempty"`

		// Fields Invalid fields, by name, and what's wrong with each.
		Fields  *map[string]string `json:"fields,omitempty"`
		Message string             `json:"message"`

		// Status The HTTP status.
		Status int32 `json:"status"`
	} `json:"error"`
}

// Conflict defines model for conflict.
type Conflict struct {
	Reason string `json:"reason"`
}

// CreatePetBody defines model for createPetBody.
type CreatePetBody struct {
	Kind *CreatePetBodyKind `json:"kind,omitempty"`
	Name string             `json:"name"`
}

// CreatePetBodyKind defines model for CreatePetBody.Kind.
type CreatePetBodyKind string

// Owner defines model for owner.
type Owner struct {
	Email openapi_types.Email `json:"email"`
}

// Pet defines model for pet.
type Pet struct {
	Born    time.Time          `json:"born"`
	Chipped bool               `json:"chipped"`
	Extra   *map[string]string `json:"extra,omitempty"`

	// Id The pet's ID.
	Id     int64    `json:"id"`
	Kind   PetKind  `json:"kind"`
	Name   string   `json:"name"`
	Owner  *Owner   `json:"owner"`
	Parent *Pet     `json:"parent,omitempty"`
	Tags   []string `json:"tags"`
	Weight float64  `json:"weight"`
}

// PetKind defines model for Pet.Kind.
type PetKind string

// ListPetsParams defines parameters for ListPets.
type ListPetsParams struct {
	Kind *string `form:"kind,omitempty" json:"kind,omitempty"`
}

// ReplacePetJSONRequestBody defines body for ReplacePet for application/json ContentType.
type ReplacePetJSONRequestBody = CreatePetBody

// CreatePetJSONRequestBody defines body for CreatePet for application/json ContentType.
type CreatePetJSONRequestBody = CreatePetBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListPets performs a GET /pets (the `ListPets` operationId) request.
	ListPets(ctx context.Context, params *ListPetsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePet performs a DELETE /pets/{id} (the `DeletePet` operationId) request.
	DeletePet(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPet performs a GET /pets/{id} (the `GetPet` operationId) request.
	GetPet(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplacePetWithBody performs a PUT /pets/{id} (the `ReplacePet` operationId) request,
	// with any type of body and a specified content type.
	ReplacePetWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReplacePet performs a PUT /pets/{id} (the `ReplacePet` operationId) request.
	// Takes a body of the `application/json` content type.
	ReplacePet(ctx context.Context, id string, body ReplacePetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePetWithBody performs a POST /stores/{store}/pets (the `CreatePet` operationId) request,
	// with any type of body and a specified content type.
	CreatePetWithBody(ctx context.Context, store string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePet performs a POST /stores/{store}/pets (the `CreatePet` operationId) request.
	// Takes a body of the `application/json` content type.
	CreatePet(ctx context.Context, store string, body CreatePetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListPets performs a GET /pets (the `ListPets` operationId) request.
func (c *Client) ListPets(ctx context.Context, params *ListPetsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPetsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeletePet performs a DELETE /pets/{id} (the `DeletePet` operationId) request.
func (c *Client) DeletePet(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePetRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPet performs a GET /pets/{id} (the `GetPet` operationId) request.
func (c *Client) GetPet(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPetRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplacePetWithBody performs a PUT /pets/{id} (the `ReplacePet` operationId) request,
// with any type of body and a specified content type.
func (c *Client) ReplacePetWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplacePetRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplacePet performs a PUT /pets/{id} (the `ReplacePet` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) ReplacePet(ctx context.Context, id string, body ReplacePetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplacePetRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePetWithBody performs a POST /stores/{store}/pets (the `CreatePet` operationId) request,
// with any type of body and a specified content type.
func (c *Client) CreatePetWithBody(ctx context.Context, store string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePetRequestWithBody(c.Server, store, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePet performs a POST /stores/{store}/pets (the `CreatePet` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) CreatePet(ctx context.Context, store string, body CreatePetJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePetRequest(c.Server, store, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPetsRequest constructs an http.Request for the ListPets method
func NewListPetsRequest(server string, params *ListPetsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Kind != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "kind", *params.Kind, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeletePetRequest constructs an http.Request for the DeletePet method
func NewDeletePetRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPetRequest constructs an http.Request for the GetPet method
func NewGetPetRequest(server string, id int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: "int64"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewReplacePetRequest calls the generic ReplacePet builder with application/json body
func NewReplacePetRequest(server string, id string, body ReplacePetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplacePetRequestWithBody(server, id, "application/json", bodyReader)
}

// NewReplacePetRequestWithBody constructs an http.Request for the ReplacePet method, with any body, and a specified content type
func NewReplacePetRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/pets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreatePetRequest calls the generic CreatePet builder with application/json body
func NewCreatePetRequest(server string, store string, body CreatePetJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePetRequestWithBody(server, store, "application/json", bodyReader)
}

// NewCreatePetRequestWithBody constructs an http.Request for the CreatePet method, with any body, and a specified content type
func NewCreatePetRequestWithBody(server string, store string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "store", store, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/stores/%s/pets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListPetsWithResponse performs a GET /pets (the `ListPets` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListPetsWithResponse(ctx context.Context, params *ListPetsParams, reqEditors ...RequestEditorFn) (*ListPetsResponse, error)

	// DeletePetWithResponse performs a DELETE /pets/{id} (the `DeletePet` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DeletePetWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*DeletePetResponse, error)

	// GetPetWithResponse performs a GET /pets/{id} (the `GetPet` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetPetWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*GetPetResponse, error)

	// ReplacePetWithBodyWithResponse performs a PUT /pets/{id} (the `ReplacePet` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	ReplacePetWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplacePetResponse, error)

	// ReplacePetWithResponse performs a PUT /pets/{id} (the `ReplacePet` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	ReplacePetWithResponse(ctx context.Context, id string, body ReplacePetJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplacePetResponse, error)

	// CreatePetWithBodyWithResponse performs a POST /stores/{store}/pets (the `CreatePet` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CreatePetWithBodyWithResponse(ctx context.Context, store string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePetResponse, error)

	// CreatePetWithResponse performs a POST /stores/{store}/pets (the `CreatePet` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CreatePetWithResponse(ctx context.Context, store string, body CreatePetJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePetResponse, error)
}

type ListPetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Pet
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListPetsResponse) GetJSON200() *[]Pet {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListPetsResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r ListPetsResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListPetsResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListPetsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListPetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPetsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeletePetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeletePetResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r DeletePetResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeletePetResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r DeletePetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeletePetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeletePetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Pet
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPetResponse) GetJSON200() *Pet {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetPetResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetPetResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r GetPetResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetPetResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetPetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReplacePetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Pet
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ReplacePetResponse) GetJSON200() *Pet {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ReplacePetResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r ReplacePetResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ReplacePetResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ReplacePetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ReplacePetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReplacePetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReplacePetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Pet
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Conflict
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreatePetResponse) GetJSON201() *Pet {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreatePetResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreatePetResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreatePetResponse) GetJSON409() *Conflict {
	return r.JSON409
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreatePetResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreatePetResponse) GetJSON500() *Error {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreatePetResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreatePetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListPetsWithResponse performs a GET /pets (the `ListPets` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListPetsWithResponse(ctx context.Context, params *ListPetsParams, reqEditors ...RequestEditorFn) (*ListPetsResponse, error) {
	rsp, err := c.ListPets(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPetsResponse(rsp)
}

// DeletePetWithResponse performs a DELETE /pets/{id} (the `DeletePet` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DeletePetWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*DeletePetResponse, error) {
	rsp, err := c.DeletePet(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePetResponse(rsp)
}

// GetPetWithResponse performs a GET /pets/{id} (the `GetPet` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetPetWithResponse(ctx context.Context, id int64, reqEditors ...RequestEditorFn) (*GetPetResponse, error) {
	rsp, err := c.GetPet(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPetResponse(rsp)
}

// ReplacePetWithBodyWithResponse performs a PUT /pets/{id} (the `ReplacePet` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ReplacePetWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReplacePetResponse, error) {
	rsp, err := c.ReplacePetWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplacePetResponse(rsp)
}

// ReplacePetWithResponse performs a PUT /pets/{id} (the `ReplacePet` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ReplacePetWithResponse(ctx context.Context, id string, body ReplacePetJSONRequestBody, reqEditors ...RequestEditorFn) (*ReplacePetResponse, error) {
	rsp, err := c.ReplacePet(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReplacePetResponse(rsp)
}

// CreatePetWithBodyWithResponse performs a POST /stores/{store}/pets (the `CreatePet` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreatePetWithBodyWithResponse(ctx context.Context, store string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePetResponse, error) {
	rsp, err := c.CreatePetWithBody(ctx, store, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePetResponse(rsp)
}

// CreatePetWithResponse performs a POST /stores/{store}/pets (the `CreatePet` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreatePetWithResponse(ctx context.Context, store string, body CreatePetJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePetResponse, error) {
	rsp, err := c.CreatePet(ctx, store, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePetResponse(rsp)
}

// ParseListPetsResponse parses an HTTP response from a ListPetsWithResponse call
func ParseListPetsResponse(rsp *http.Response) (*ListPetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Pet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeletePetResponse parses an HTTP response from a DeletePetWithResponse call
func ParseDeletePetResponse(rsp *http.Response) (*DeletePetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPetResponse parses an HTTP response from a GetPetWithResponse call
func ParseGetPetResponse(rsp *http.Response) (*GetPetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Pet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseReplacePetResponse parses an HTTP response from a ReplacePetWithResponse call
func ParseReplacePetResponse(rsp *http.Response) (*ReplacePetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReplacePetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Pet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreatePetResponse parses an HTTP response from a CreatePetWithResponse call
func ParseCreatePetResponse(rsp *http.Response) (*CreatePetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Pet
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
